### PR TITLE
Fix active_support loading issue

### PR DESCRIPTION
**Pull request by wdperson**
@josephbridgwaterrowe any chance you could get this merged in to this active_record_migrations branch?  We use this on our production servers and would like to have the PR you merged in to master here as well.

### CODE REVIEW

**Comment by wdperson** [comment]
@josephbridgwaterrowe also, we are interested in contributing on this as well, so if you want to add me @wdperson and @samsongz on the project we are more than happy to help.

**Comment by wdperson** [comment]
@josephbridgwaterrowe just wanted to check in on this to see if you could help out on these two issues, sorry, not trying to be a pain.

**Comment by samsongz** [comment]
@josephbridgwaterrowe any more info here on getting this rebased? we're considering forking your branch if we can't get this resolved soon. we're happy to help maintain this but need to take action soon on our side, it's causing some repetitive problems

**Comment by josephbridgwaterrowe** [comment]
@wdperson, @samsongz terribly sorry for the delay, merging now.

**Comment by josephbridgwaterrowe** [comment]
@wdperson @samsongz Really sorry again for the delay, to clarify (if I haven't already lost you) you would like the active_record_migrations merged into master?

**Comment by wdperson** [comment]
@josephbridgwaterrowe no worries, thanks for getting this taken care of.  I think it is good to merge in to master.  I'd have to review it in more detail, however, we use it in production without any issues that I am aware of.

**Comment by josephbridgwaterrowe** [comment]
So, I know I've been terrible with my response times (kind of busy at home and work)... but I would like to get the active_record_migrations merged into master, however I would like to split it up because there are a couple of unrelated changes in there.

@wdperson how about I break it up, and you can review the smaller PR's? Also, which version are you using in production?

**Comment by wdperson** [comment]
@josephbridgwaterrowe that sounds good (smaller PRs).  This is what we are using in production:

remote: https://github.com/josephbridgwaterrowe/promiscuous.git
revision: 10ada49df618d7d4a543298a87d11e927adfd985
branch: active_record_migrations
specs:
  promiscuous (1.0.0.beta6)

**Pull request merged**
