### PR TITLE
ActiveRecord Migration Checks

### PR DESCRIPTION
**Pull request by josephbridgwaterrowe**
Move the ActiveRecord schema checks into a CLI driven process.

Add the CLI command "migrations", callable using the command line
"bundle exec promiscuous migrations".

This new CLI command checks for the presence of the transport_collection
table in the database and that all publishers and subscribers have
the necessary "_v" column.

### CODE REVIEW

**Comment by josephbridgwaterrowe** [comment]
@wdperson First PR for the migration work, although this still needs to be rebased against master.

How do you feel about me rebasing out my merge from master to clean up the commit history? The thought of rebasing master makes me cringe, but in this instance I don't think its a big deal. 😄 

Also, I would like to add some documentation for this process, but it doesn't apply to Mongo... not sure at this point where it really fits into the docs without a new set of Getting Started docs. Thoughts?

**Comment by wdperson** [comment]
@josephbridgwaterrowe I think this PR looks good.  I think it is fine to rebase out your merge from master.  I like a clean commit history and if nothing gets messed up and it improves it, I am all for it.  Not sure what to do on the documentation...

**Comment by josephbridgwaterrowe** [comment]
@wdperson rebased with master and added some docs.

Will merge if you agree its good to go (finally), once merged I hope to get the other changes in once and for all:

- Savepoint changes
- Virtual host support

Before working on the others, I would like to have a brief conversation about MySQL support and the issues I had (i.e. problems with MySQL but not Postgres). FWIW, I love MySQL but find myself increasingly using Postgres.

**Comment by wdperson** [comment]
@josephbridgwaterrowe I took a look at this after your updates and I think this is good to go from what I can see.

**Pull request merged**
